In [15]:
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print ('names \n', names)
names == 'Bob'

names 
 ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


array([ True, False, False,  True, False, False, False])

In [21]:
# utilizar aquí la función 'randn' de 'numpy.random' para
# generar algunos datos aleatorios con distribución normal:
# 
data = np.random.randn (7, 4)
print ('data \n', data)

data 
 [[-1.30235616  0.23123907  0.20075285 -0.40903462]
 [-0.73581305  1.60629578 -0.14694842 -1.56527475]
 [-0.10196571  0.33013397  0.216767   -1.64594304]
 [-0.11732481  0.39931432  1.2858626   0.30679956]
 [ 0.04431086  0.29819362  0.40097879  0.62672416]
 [-0.91596511 -1.14547615  1.19906895 -0.27170013]
 [ 0.15043211  1.41845205  1.43667539 -0.62554215]]


In [22]:
# Poner los valores negativos de los datos a 0: 
data[data < 0] = 0
data

array([[0.        , 0.23123907, 0.20075285, 0.        ],
       [0.        , 1.60629578, 0.        , 0.        ],
       [0.        , 0.33013397, 0.216767  , 0.        ],
       [0.        , 0.39931432, 1.2858626 , 0.30679956],
       [0.04431086, 0.29819362, 0.40097879, 0.62672416],
       [0.        , 0.        , 1.19906895, 0.        ],
       [0.15043211, 1.41845205, 1.43667539, 0.        ]])