In [7]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b=np.array([1,2,3.0])
print(a)

[1 2 3]


In [10]:
print('tipo de datos a',a.dtype)
print('tipo de datos b',b.dtype)

int32
float64


In [11]:
# forzando el tipo del array
c=np.array([2,4,6], dtype=float)
print(c)

[2. 4. 6.]


In [12]:
# convirtiendo array c para enteros
d=c.astype(int)
print(d)

[2 4 6]


In [16]:
# indexación de arrays
a = np.array([
    [1,2,3],
    [4,5,6]
])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a[0,0]

1

In [19]:
e=a[0:2,1:3]
print(e)

[[2 3]
 [5 6]]


In [20]:
e=a[:,1:3]
print(e)

[[2 3]
 [5 6]]
