En el ejemplo siguiente se muestra cómo utilizar\
el atributo 'dtype' para generar arrays de elementos\
de valores enteros, flotantes y complejos:

In [5]:
import numpy as np

In [6]:
arr1 = np.array([1, 2, 3], dtype=int)
print('array 1', arr1,'\n')
arr2 = np.array([1, 2, 3], dtype=float)
print('array 2', arr2,'\n')
arr3 = np.array([1, 2, 3], dtype=complex)
print('array 3', arr3,'\n')

array 1 [1 2 3] 

array 2 [1. 2. 3.] 

array 3 [1.+0.j 2.+0.j 3.+0.j] 



Cálculos con arrays, el tipo de datos puede ser \
modificado de un tipo a otro, si lo requiere la operación. \
Por ejemplo, si se suman arrays de valor flotante y de valor complejo,\
el array resultante es un array de valor complejo

In [7]:
d1 = np.array([1, 2, 3], dtype=float)
d2 = np.array([1, 2, 3], dtype=complex)
ds = d1 + d2
print('ds: ', ds)
ds.dtype

ds:  [2.+0.j 4.+0.j 6.+0.j]


dtype('complex128')

In [13]:
datos0 = np.array([[1, 2], [3, 4]])
print('datos0: \n', datos0)
datos1 = np.reshape(data, (1, 4))
print('datos1: \n', datos1)
datos2 =  datos1.reshape(4)
print('datos2: \n', datos2)

datos0: 
 [[1 2]
 [3 4]]
datos1: 
 [[1 2 3 4]]
datos2: 
 [1 2 3 4]


In [19]:
datos = np.array([[1, 2], [3, 4]])
print('reshape_1: \n', np.reshape(datos, (1, 4)))
print('reshape_2: \n', np.reshape(datos, 4))
print('datos: \n', datos)

reshape_1: 
 [[1 2 3 4]]
reshape_2: 
 [1 2 3 4]
datos: 
 [[1 2]
 [3 4]]


In [21]:
suma = np.add(datos, datos)
suma

array([[2, 4],
       [6, 8]])

In [23]:
resta = np.subtract(datos*4, datos)
resta

array([[ 3,  6],
       [ 9, 12]])

### Operaciones aritméticas
Las operaciones aritméticas estándar\
con los arrays de NumPy \
realizan operaciones elemento a elemento.\
Ejemplos con arrays del mismo tamaño

In [32]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print ('x: \n', x)
print ('y: \n', y)

x: 
 [[1 2]
 [3 4]]
y: 
 [[5 6]
 [7 8]]


In [33]:
print('suma: \n', x + y)

suma: 
 [[ 6  8]
 [10 12]]


In [38]:
print('resta: \n', y-x)

resta: 
 [[4 4]
 [4 4]]


In [35]:
print('multplicación: \n', y*x)

multplicación: 
 [[ 5 12]
 [21 32]]


In [37]:
print('división: \n', y/x)

división: 
 [[5.         3.        ]
 [2.33333333 2.        ]]


En las operaciones entre escalares y arrays,\
el valor del escalar se aplica a cada \
elemento del array:

In [39]:
print(' mult por 2 \n',x * 2)

 mult por 2 
 [[2 4]
 [6 8]]


In [41]:
print('2 elev a x: \n',2 ** x)

2 elev a x: 
 [[ 2  4]
 [ 8 16]]


In [43]:
print('partido por 2: \n',y / 2)

partido por 2: 
 [[2.5 3. ]
 [3.5 4. ]]


In [47]:
x = np.linspace(-1, 1, 11)
print('x: \n', x)

y = np.sin(np.pi * x)
print('y : \n', np.round(y, decimals=4))

x: 
 [-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]
y : 
 [-0.     -0.5878 -0.9511 -0.9511 -0.5878  0.      0.5878  0.9511  0.9511
  0.5878  0.    ]


In [51]:
# operaciones identicas
z =  np.add(np.sin(x) ** 2, np.cos(x) ** 2)
print('z: \n',z)

w = np.sin(x) ** 2 + np.cos(x) ** 2
            
print('w : \n', w )

z: 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
w : 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [54]:
# Dos formas para obtener media
data = np.random.normal(size=(15,15))

m_1  = np.mean(data)
m_2  = data.mean()

print ('m_1: \n', m_1)
print ('m_2: \n', m_2)

m_1: 
 0.1148553705433423
m_2: 
 0.1148553705433423
