In [1]:
import numpy as np
np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1,'\n')

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print (arr2)

[6.  7.5 8.  0.  1. ] 

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
# numero de elementos del array
ne = arr2.ndim 
print (ne,'\n')
# tamaño del array
tam = arr2.shape
print (tam,'\n')
# tipo del array
tipo = arr2.dtype
print (tipo,'\n')
# crear un array vacío
arr_vacio= np.empty ((2,3,2))
print (arr_vacio)

2 

(2, 4) 

int32 

[[[1.01855798e-312 1.06099790e-312]
  [1.01855798e-312 9.54898106e-313]
  [1.06099790e-312 1.03977794e-312]]

 [[1.23075756e-312 1.01855798e-312]
  [1.10343781e-312 9.76118064e-313]
  [1.16709769e-312 1.90979621e-312]]]


In [1]:
# rebanar un array
import numpy as np
vector = np.array([ 0, 1, 2, 3, 4, 12, 12, 12, 8, 9])
rebanada_vector = vector [5:8]
print (rebanada_vector)

[12 12 12]


In [11]:
# Transposición de matrices 
matriz = np.arange(15).reshape((3, 5))
# 3 filas con 5 columnas
print (matriz,'\n')
matriz_t = matriz.T
print (matriz_t)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [12]:
# Transposición de matrices 
matriz = np.random.randn(6, 3)
print (matriz,'\n')
matriz_t = np.transpose(matriz)
print (matriz_t)

[[-0.99432075  0.21971841  0.26949228]
 [ 0.21087412 -0.09130436 -1.63828065]
 [-0.75466134  0.49297376 -0.25547996]
 [-1.16037725  0.07085668  0.79416343]
 [-1.94319906  0.24796555 -0.55319443]
 [-1.24738373  0.6891078   0.34703197]] 

[[-0.99432075  0.21087412 -0.75466134 -1.16037725 -1.94319906 -1.24738373]
 [ 0.21971841 -0.09130436  0.49297376  0.07085668  0.24796555  0.6891078 ]
 [ 0.26949228 -1.63828065 -0.25547996  0.79416343 -0.55319443  0.34703197]]


In [69]:
# Meshgrid

# Es la función que crea una cuadrícula rectangular a partir de 2 matrices unidimensionales, 
# que denotan la indexación matricial o cartesiana. Pertenence al módulo numpy. 
# Las matrices de coordenadas se devuelven a partir de los vectores de coordenadas.

import numpy as np
n1, n2 = (5, 3)
a = np.linspace(0, 1, n1)
b = np.linspace(0, 1, n2)
aa, bb = np.meshgrid(a, b)
print('aa = ', aa)
print('bb = ', bb)

aa =  [[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
bb =  [[0.  0.  0.  0.  0. ]
 [0.5 0.5 0.5 0.5 0.5]
 [1.  1.  1.  1.  1. ]]


In [32]:
# programando con matrices

# 1000 puntos igualmente espaciados
puntos = np.arange(-5, 5, 0.01) 

x, y = np.meshgrid(puntos, puntos)
print("x = ")
print (x)
print("y = ")
print (y)

z = np.sqrt(x ** 2 + y ** 2)
print("z = ")
print (z)

x = 
[[-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 ...
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]]
y = 
[[-5.   -5.   -5.   ... -5.   -5.   -5.  ]
 [-4.99 -4.99 -4.99 ... -4.99 -4.99 -4.99]
 [-4.98 -4.98 -4.98 ... -4.98 -4.98 -4.98]
 ...
 [ 4.97  4.97  4.97 ...  4.97  4.97  4.97]
 [ 4.98  4.98  4.98 ...  4.98  4.98  4.98]
 [ 4.99  4.99  4.99 ...  4.99  4.99  4.99]]
z = 
[[7.07106781 7.06400028 7.05693985 ... 7.04988652 7.05693985 7.06400028]
 [7.06400028 7.05692568 7.04985815 ... 7.04279774 7.04985815 7.05692568]
 [7.05693985 7.04985815 7.04278354 ... 7.03571603 7.04278354 7.04985815]
 ...
 [7.04988652 7.04279774 7.03571603 ... 7.0286414  7.03571603 7.04279774]
 [7.05693985 7.04985815 7.04278354 ... 7.03571603 7.04278354 7.04985815]
 [7.06400028 7.05692568 7.04985815 ... 7.04279774 7.04985815 7.05692568]]


In [24]:
# Código para generar  una figura
x = np.linspace(-4, 4, 9)
y = np.linspace(-5, 5, 11)
 
# La función meshgrid devuelve 
# dos matrices bidimensionales
x_1, y_1 = np.meshgrid(x, y)
 
print("x_1 = ")
print(x_1)
print("y_1 = ")
print(y_1)

x_1 = 
[[-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]
 [-4. -3. -2. -1.  0.  1.  2.  3.  4.]]
y_1 = 
[[-5. -5. -5. -5. -5. -5. -5. -5. -5.]
 [-4. -4. -4. -4. -4. -4. -4. -4. -4.]
 [-3. -3. -3. -3. -3. -3. -3. -3. -3.]
 [-2. -2. -2. -2. -2. -2. -2. -2. -2.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 2.  2.  2.  2.  2.  2.  2.  2.  2.]
 [ 3.  3.  3.  3.  3.  3.  3.  3.  3.]
 [ 4.  4.  4.  4.  4.  4.  4.  4.  4.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.]]


In [36]:
arr_x = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
arr_y = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
resultado = np.where(cond, arr_x, arr_y)
print('resultado = ')
print(resultado)

resultado = 
[1.1 2.2 1.3 1.4 2.5]


In [43]:
# Suponer un array de datos 
# generados aleatoriamente y 
# sustituir todos los valores 
# positivos por 2 y todos los 
# valores negativos por -2. 
arr = np.random.randn(4, 4)
print('arr= ')
print (arr)
# array de booleanos
arr_b = arr > 0
print('arr_b = ')
print (arr_b)
# nuevo array 
arr_n = np.where (arr > 0, 2, -2)
print('arr_n = ')
print (arr_n)

arr= 
[[ 0.45769727  0.52756914 -1.39857437 -0.19214542]
 [ 0.46845577 -0.64642969 -1.84432371  0.4921804 ]
 [ 0.61645909 -1.09819108  0.8011581  -1.41575393]
 [-0.31540258 -0.11053938 -0.4860375  -0.18358214]]
arr_b = 
[[ True  True False False]
 [ True False False  True]
 [ True False  True False]
 [False False False False]]
arr_n = 
[[ 2  2 -2 -2]
 [ 2 -2 -2  2]
 [ 2 -2  2 -2]
 [-2 -2 -2 -2]]


In [70]:
# Mathematical and Statistical Methods
arr = np.random.randn(5, 4)
print('arr= ')
print (arr)
media = arr.mean()
suma  = arr.sum()
print ('     media = ', media) 
print ('      suma = ', suma)

media_col = arr.mean(axis=1)
# significa "calcular la media a través de las columnas" . axis=1
suma_filas = arr.sum(axis=0)
# significa "calcular la suma en las filas". axis=0
print (' media_col = ', media_col)
print ('suma_filas = ', suma_filas)

arr= 
[[ 0.5524261  -1.64572697 -0.25720805 -1.85595879]
 [-0.46110184  1.2463537  -0.52735632 -1.47591786]
 [ 0.23324094  0.01210284  1.05744021  1.79460824]
 [-0.33735575 -0.17977867  0.18931428  0.13279537]
 [-0.5651362  -0.21630628  0.51638187  2.02787885]]
     media =  0.012034782860922499
      suma =  0.24069565721845
 media_col =  [-0.80161693 -0.30450558  0.77434806 -0.04875619  0.44070456]
suma_filas =  [-0.57792676 -0.78335539  0.97857199  0.62340581]


In [72]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print('arr= ')
print (arr)
print('arr.cumsum= ')
print (arr.cumsum (axis=0))
print('arr.cumprod= ')
print (arr.cumprod(axis=1))

arr= 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
arr.cumsum= 
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
arr.cumprod= 
[[  0   0   0]
 [  3  12  60]
 [  6  42 336]]


In [88]:
arr = np.random.randn(6)
print('arr = ')
print (arr)
arr_ord = np.sort(arr)
print('arr_ord = ')
print (arr_ord)
arr = np.random.randn(5, 3)
print('arr = ')
print (arr)
arr_ord = np.sort(arr)
print('arr_ord = ')
print (arr_ord)

arr = 
[-0.51469667 -1.07820686  0.3170031  -0.868678    0.74441081 -0.11843787]
arr_ord = 
[-1.07820686 -0.868678   -0.51469667 -0.11843787  0.3170031   0.74441081]
arr = 
[[ 0.8923967  -1.54506691  0.20978315]
 [ 0.60209997 -1.55358583 -0.5236397 ]
 [ 0.25918586  0.13702275  0.41452626]
 [-0.85139887  1.68846228  0.16217555]
 [-1.40881694 -1.2951023   0.21506767]]
arr_ord = 
[[-1.54506691  0.20978315  0.8923967 ]
 [-1.55358583 -0.5236397   0.60209997]
 [ 0.13702275  0.25918586  0.41452626]
 [-0.85139887  0.16217555  1.68846228]
 [-1.40881694 -1.2951023   0.21506767]]


In [93]:
import numpy as np 
   
a = np.array([[11, 12, 5], 
              [15, 6,10], 
              [10, 8, 12], 
              [12,15,8], 
              [34, 78, 90]]) 

sorted_array = np.sort(a) 
print('El array ordenado es:')
print(sorted_array) 

El array ordenado es:
[[ 5 11 12]
 [ 6 10 15]
 [ 8 10 12]
 [ 8 12 15]
 [34 78 90]]


In [95]:
import numpy as np 
   
a = np.array([[11, 12, 5], [15, 6,10], [10, 8, 12], [12,15,8], [34, 78, 90]]) 

sorted_array = np.sort(a, axis= None) 
print('El array ordenado es:')
print(sorted_array) 

El array ordenado es:
[ 5  6  8  8 10 10 11 12 12 12 15 15 34 78 90]


In [97]:
import numpy as np 
a = np.array([[11, 12, 5], [15, 6,10], [10, 8, 12], [12,15,8]]) 
print('El array original es:')
print(a) 
sorted_array = np.sort(a, axis= 0) 
print('El array ordenado es:')
print(sorted_array) 

El array original es:
[[11 12  5]
 [15  6 10]
 [10  8 12]
 [12 15  8]]
El array ordenado es:
[[10  6  5]
 [11  8  8]
 [12 12 10]
 [15 15 12]]
